if __name__ == "__main__":
    import subprocess
    from datetime import datetime as dt
    import sys

    README_PATH = "../README.md"
    README_GEN_PATH = README_PATH + ".build"
    VERSION_TAG = sys.argv[1][1:-1]
    VERSION_MAJOR = VERSION_TAG.split(".")[0]
    VERSION_MD_PATH = "../book/versions"

    with open(README_GEN_PATH, "r") as f:
        readme = {"content": f.read()}

        def put(var, text):
            readme["content"] = readme["content"].replace("{{" + var + "}}", text)

        put("DATE", str(dt.now()))
        put("VERSION", VERSION_TAG)
        put("AUTHOR", "[Ethan Uppal](https://www.ethanuppal.com)")

        with open(f"{VERSION_MD_PATH}/{VERSION_MAJOR}.md", "r") as md:
            put("VERSIONMD", md.read())

        with open(README_PATH, "w") as f:
            f.write(
                "<!-- THIS FILE IS GENERATED AUTOMATICALLY. -->\n<!-- DO NOT EDIT THIS FILE. -->\n<!-- EDIT README.md.build INSTEAD. -->\n"
                + readme["content"]
            )
